### PR TITLE
Add file consistency Check

### PR DESCRIPTION
**Pull request by certara-msale**

### CODE REVIEW

**Comment by certara-amazur** [comment]
Hi Mark,

Template cannot check this because NM and NLME have different comment syntax. So this check must be performed on another level, DarwinApp seems the most suitable place for that.

See https://github.com/certara/pyDarwin/commit/b808c69d9cd73bde4d6063877d853dfb3b73f208

**Comment by certara-msale** [comment]
Thanks Alex, didn't think of that. May need some help putting it in the right place.


Mark Sale M.D.
Vice President
Integrated Drug Development
***@***.***
Remote-Forestville CA
Office Hours 9 AM - 5 PM Eastern Time
+1 302-516-1684
www.certara.com
[Certara Logo]

**Comment by certara-amazur** [comment]
It's already done.

**Comment by certara-msale** [comment]
Thanks


Mark Sale M.D.
Vice President
Integrated Drug Development
***@***.***
Remote-Forestville CA
Office Hours 9 AM - 5 PM Eastern Time
+1 302-516-1684
www.certara.com
[Certara Logo]

**Pull request closed without merging**
